tasks:
  - name: Install RStudio
    init: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt install -y r-base r-base-core r-recommended r-base-dev gdebi-core build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      wget https://rstudio.org/download/latest/stable/server/jammy/rstudio-server-latest-amd64.deb
      gp ports visibility 8787:public
      sudo gdebi --n rstudio-server-latest-amd64.deb
      sudo rstudio-server start
      echo "********************************************"
      echo "Now you have to complete the creation of a new user: type a password, confirm it, accept the other defaults and complete the user. Then login to the RStudio Server using this new user and their password "
      sudo adduser rstudio
